import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import TwitterFeed from "../components/TwitterFeed";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>LieSocial</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-black">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Welcome to LieSocial
          </h1>
          <TwitterFeed />
        </div>
      </main>
    </>
  );
};

export default Home;
